version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - rm -rf node_modules/
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - node_modules/
